export const mockServices = [
  {
    slug: "dugun-nisan-kina",
    category: "dugun" as const,
    title: "Düğün, Nişan & Kına",
    shortDescription: "En özel gününüzü unutulmaz kılıyoruz. Dekordan catering'e, fotoğraftan müziğe her detay elimizde.",
    description: `Düğün organizasyonunuzda sizi en özel hissettirecek her şeyi planlıyoruz. 15 yılı aşkın deneyimimizle yüzlerce çifte hayallerindeki düğünü yaşattık.\n\nMekân seçiminden dekorasyon tasarımına, davetiye hazırlığından akşam programına kadar tüm süreç profesyonel ekibimiz tarafından yönetilir.`,
    features: [
      "Mekân keşfi ve rezervasyon",
      "Floral & tematik dekorasyon",
      "Yemek & ikram organizasyonu",
      "Fotoğraf ve video çekim paketi",
      "Müzik & DJ hizmeti",
      "Gelin arabası & ulaşım",
      "Davetiye & baskı tasarımı",
      "Koordinatör eşliği (gün boyunca)",
    ],
    priceRange: "₺45.000 — ₺200.000+",
    gradient: "from-rose-300 to-rose-500",
    icon: "Heart",
    order: 1,
  },
  {
    slug: "dogum-gunu-baby-shower",
    category: "dogum_gunu" as const,
    title: "Doğum Günü & Baby Shower",
    shortDescription: "Çocuğunuzun ya da sevdiğinizin özel gününü masalsı bir kutlamaya dönüştürüyoruz.",
    description: `Doğum günü kutlamalarında her yaş grubuna özel, kişiye özgü temalar oluşturuyoruz. Balondan maskota, pastadan sürpriz sahnelerine kadar her detayı mükemmel planlıyoruz.\n\nBaby shower organizasyonlarında anne adayını özel hissettiren zarif konseptler ve pratik hediye yönetimi sunuyoruz.`,
    features: [
      "Kişiye özel tema ve dekorasyon",
      "Pasta & ikram koordinasyonu",
      "Sürpriz sahne planlaması",
      "Fotoğraf köşesi (photo booth)",
      "Balon & çiçek tasarımı",
      "Animatör & eğlence programı",
      "Hediye masası düzeni",
      "Davet kartı tasarımı",
    ],
    priceRange: "₺8.000 — ₺35.000",
    gradient: "from-amber-300 to-amber-500",
    icon: "Gift",
    order: 2,
  },
  {
    slug: "kurumsal-etkinlikler",
    category: "kurumsal" as const,
    title: "Kurumsal Etkinlikler",
    shortDescription: "Şirket lansmanlarından team-building etkinliklerine, konferanstan gala yemeklerine profesyonel çözümler.",
    description: `Kurumsal etkinliklerinizde markanızın değerlerini yansıtan, katılımcılarınızı etkileyen deneyimler tasarlıyoruz. Teknik altyapıdan kurumsal hediye koordinasyonuna kadar tüm süreç kontrol altında.\n\nYılbaşı yemeklerinden ürün lansmanlarına, eğitim programlarından açılış törenlerine kadar her ölçekte etkinlik yönetimi yapıyoruz.`,
    features: [
      "Mekân analizi ve düzen tasarımı",
      "AV teknik altyapı (ses, ışık, projeksiyon)",
      "Kurumsal dekorasyon & branding",
      "Catering & kokteyl organizasyonu",
      "Kurumsal hediye koordinasyonu",
      "Konuşmacı & program yönetimi",
      "Basın ve davetli yönetimi",
      "Canlı yayın & kayıt",
    ],
    priceRange: "₺25.000 — ₺500.000+",
    gradient: "from-sky-300 to-sky-500",
    icon: "Briefcase",
    order: 3,
  },
  {
    slug: "mezuniyet-sunnet",
    category: "mezuniyet" as const,
    title: "Mezuniyet & Sünnet",
    shortDescription: "Hayatın dönüm noktalarını kutlamak için özenle hazırlanmış organizasyonlar.",
    description: `Mezuniyet törenleri ve sünnet organizasyonlarında ailelere en özel anları yaşatıyoruz. Çocuğunuzun bu büyük gününü unutulmaz kılmak için titizlikle çalışıyoruz.\n\nGeleneksel ve modern konseptleri harmanlayarak, aile büyüklerini de memnun eden, çocukları da eğlendiren dengeli programlar oluşturuyoruz.`,
    features: [
      "Salon ve mekân organizasyonu",
      "Tematik dekorasyon tasarımı",
      "Özel pasta & tatlı masası",
      "Animatör ve eğlence programı",
      "Fotoğraf ve video hizmeti",
      "Kıyafet koordinasyonu (sünnet için)",
      "Aile büyüklerine özel ikram",
      "Hediyelik eşya koordinasyonu",
    ],
    priceRange: "₺12.000 — ₺60.000",
    gradient: "from-emerald-300 to-emerald-500",
    icon: "GraduationCap",
    order: 4,
  },
];

export const mockGallery = [
  { id: "1", title: "Bahçe Düğünü — Zeynep & Burak", category: "Düğün", gradient: "from-rose-200 to-rose-400", year: "2024" },
  { id: "2", title: "Tech Startup Lansmanı", category: "Kurumsal", gradient: "from-sky-200 to-sky-400", year: "2024" },
  { id: "3", title: "Selin'in 1. Yaş Günü", category: "Doğum Günü", gradient: "from-amber-200 to-amber-400", year: "2024" },
  { id: "4", title: "Nişan Töreni — Leyla & Emre", category: "Nişan", gradient: "from-pink-200 to-pink-400", year: "2023" },
  { id: "5", title: "Sünnet Şöleni — Yusuf", category: "Sünnet", gradient: "from-emerald-200 to-emerald-400", year: "2023" },
  { id: "6", title: "MBA Mezuniyeti — 2023", category: "Mezuniyet", gradient: "from-violet-200 to-violet-400", year: "2023" },
  { id: "7", title: "Baby Shower — Elif Hanım", category: "Baby Shower", gradient: "from-fuchsia-200 to-fuchsia-400", year: "2024" },
  { id: "8", title: "Yılbaşı Galası — Artı Teknoloji", category: "Kurumsal", gradient: "from-indigo-200 to-indigo-400", year: "2023" },
  { id: "9", title: "Kına Gecesi — Derya", category: "Kına", gradient: "from-orange-200 to-orange-400", year: "2024" },
];

export const mockTestimonials = [
  {
    name: "Ayşe & Mehmet K.",
    event: "Düğün Organizasyonu",
    comment: "Düğünümüzün her detayı mükemmeldi. Odhun ekibi gerçekten işinin ehli; saatlerce uğraşacağımız konuları tek seferde hallettiler. Minnettarız!",
    rating: 5,
    date: "Ekim 2024",
  },
  {
    name: "Zeynep Aydın",
    event: "Kurumsal Lansman",
    comment: "Şirketimizin ürün lansmanı için çalıştık. Profesyonel yaklaşım, zamanında teslimat ve misafirlerimizin aldığı hizmet kalitesi beklentilerimizi aştı.",
    rating: 5,
    date: "Eylül 2024",
  },
  {
    name: "Fatma Çelik",
    event: "Baby Shower",
    comment: "Kızımın baby shower'ı için harika bir organizasyon kurdular. Dekorasyon, ikramlar ve sürpriz anlar için özel düşündükleri her detay için teşekkürler.",
    rating: 5,
    date: "Ağustos 2024",
  },
  {
    name: "Hasan Yılmaz",
    event: "Sünnet Organizasyonu",
    comment: "Oğlumun sünnet düğünü için Odhun'u tercih ettik. Hem biz hem de misafirlerimiz çok memnun kaldı. Özellikle animatör hizmeti ve dekorasyon muhteşemdi.",
    rating: 5,
    date: "Temmuz 2024",
  },
  {
    name: "Selin Arslan",
    event: "Mezuniyet Töreni",
    comment: "Üniversite mezuniyetimizi çok özel bir hale getirdiler. Koordinatör hanım gün boyunca yanımızdaydı, hiç bir sorunla uğraşmak zorunda kalmadık.",
    rating: 5,
    date: "Haziran 2024",
  },
  {
    name: "Murat & Ceren D.",
    event: "Nişan Töreni",
    comment: "Nişan dekorasyonu hayallerimizin de ötesindeydi. Floral düzenlemeler özellikle çok şıktı. Düğünümüzü de Odhun ile yapacağız!",
    rating: 5,
    date: "Mayıs 2024",
  },
];

export const mockStats = [
  { number: "500+", label: "Mutlu Çift" },
  { number: "15+", label: "Yıllık Deneyim" },
  { number: "1200+", label: "Etkinlik" },
  { number: "%100", label: "Müşteri Memnuniyeti" },
];
